
package me.romanow.brs.javaview;

import java.awt.FileDialog;
import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.InputStreamReader;
import me.romanow.brs.database.DBItem;
import me.romanow.brs.database.DBStudent;
import me.romanow.brs.database.DBUser;

public class StudentWindow extends javax.swing.JFrame {

    private AdminWindow parent=null;
    private TableComboBox studentList=new TableComboBox();
   
    public StudentWindow(AdminWindow parent0) throws Throwable {
        initComponents();
        setTitle("Студенты");
        this.parent = parent0;
        setBounds(250, 220, 300, 150);
        parent.studentItem=null;
        studentList=new TableComboBox(StudentList, new DBStudent(),new TableChoiceListener(){
        public void onSelect(DBItem item) {
            parent.studentItem=(DBStudent)item;
            }
        });
        studentList.setList(parent.conn.getList(DBStudent.class,parent.groupItem));    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button2 = new javax.swing.JButton();
        button5 = new javax.swing.JButton();
        button29 = new javax.swing.JButton();
        StudentList = new javax.swing.JComboBox();
        button30 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        button2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        button2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable-mdpi/add.png"))); // NOI18N
        button2.setBorder(null);
        button2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button2MouseClicked(evt);
            }
        });
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        getContentPane().add(button2);
        button2.setBounds(20, 50, 30, 30);

        button5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        button5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable-mdpi/remove.png"))); // NOI18N
        button5.setBorder(null);
        button5.setName(""); // NOI18N
        button5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button5MouseClicked(evt);
            }
        });
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });
        getContentPane().add(button5);
        button5.setBounds(210, 50, 30, 30);

        button29.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        button29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable-mdpi/refresh.png"))); // NOI18N
        button29.setBorder(null);
        button29.setName(""); // NOI18N
        button29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button29MouseClicked(evt);
            }
        });
        button29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button29ActionPerformed(evt);
            }
        });
        getContentPane().add(button29);
        button29.setBounds(150, 50, 30, 30);

        StudentList.setEditable(true);
        StudentList.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(StudentList);
        StudentList.setBounds(20, 20, 220, 21);

        button30.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        button30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable-mdpi/download.png"))); // NOI18N
        button30.setBorder(null);
        button30.setName(""); // NOI18N
        button30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button30MouseClicked(evt);
            }
        });
        button30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button30ActionPerformed(evt);
            }
        });
        getContentPane().add(button30);
        button30.setBounds(80, 50, 30, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button2MouseClicked
        if (evt.getButton()==3){
            parent.onErrorMessage("Добавить студента");
        }
    }//GEN-LAST:event_button2MouseClicked

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        parent.login = new DBUser();
        new UserWindow(parent.login,false, new YesNoListener(){
            @Override
            public void onYes() {
                parent.addStudent();
                dispose();
                }
            @Override
            public void onNo() {
                dispose();
                }
            });
    }//GEN-LAST:event_button2ActionPerformed

    private void button5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button5MouseClicked
        if (evt.getButton()==3){
            parent.onErrorMessage("Удалить студента");
        }
    }//GEN-LAST:event_button5MouseClicked

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        parent.removeStudent();
        dispose();
    }//GEN-LAST:event_button5ActionPerformed

    private void button29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button29MouseClicked
        if (evt.getButton()==3){
            parent.onErrorMessage("Обновить данные студента");
        }
    }//GEN-LAST:event_button29MouseClicked

    private void button29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button29ActionPerformed
        if (parent.studentItem==null){
            parent.onErrorMessage("Не выбран студент");
            return;
            }
        parent.login = new DBUser();
        parent.login.setPass(parent.studentItem.getPass());
        parent.login.setName(parent.studentItem.getName());
        parent.login.setAdmin(false);
        new UserWindow(parent.login,false, new YesNoListener(){
            @Override
            public void onYes() {
                parent.updateStudent();
                dispose();
                }
            @Override
            public void onNo() {
                dispose();
                }
            });

    }//GEN-LAST:event_button29ActionPerformed

    private void button30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button30MouseClicked
        if (evt.getButton()==3){
            parent.onErrorMessage("Загрузить список группы из текстового файла");
        }
    }//GEN-LAST:event_button30MouseClicked

    private void button30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button30ActionPerformed
        parent.onErrorMessage("");
        FileDialog dlg=new FileDialog(this,"Импорт списка студентов",FileDialog.LOAD);
        dlg.setFile("*.txt");
        dlg.show();
        String path=dlg.getDirectory()+dlg.getFile();
        if (path==null) return;
        String s="";
        try	{
            BufferedReader si=new BufferedReader(new InputStreamReader(new FileInputStream(path),"UTF-8"));
            parent.conn.deleteLinked(DBStudent.class, parent.groupItem);
            while (true){
            	String ss=si.readLine();
            	if (ss==null) break;
            	if (ss.length()==0) continue;
                char cc[]=ss.toCharArray();
                int i=0;
                for(i=0;i < cc.length && (cc[i]==' ' || cc[i]=='\t' || cc[i]>='0' && cc[i]<='9');i++);
                if (i==cc.length)
                    continue;
                ss=ss.substring(i);
                int idx = ss.indexOf("\t");
                if (idx!=-1)
                    ss = ss.substring(0,idx);
                parent.conn.insert(new DBStudent(ss,parent.groupItem.getId()));
                }
            si.close();
            parent.studentItem=null;
            this.dispose();
            }
        catch (Throwable ee) { parent.fatal(ee);}
    }//GEN-LAST:event_button30ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox StudentList;
    private javax.swing.JButton button2;
    private javax.swing.JButton button29;
    private javax.swing.JButton button30;
    private javax.swing.JButton button5;
    // End of variables declaration//GEN-END:variables
}
