
package me.romanow.brs.javaview;

import java.util.logging.Level;
import java.util.logging.Logger;
import me.romanow.brs.database.DBItem;
import me.romanow.brs.database.DBPermission;
import me.romanow.brs.database.DBRating;
import me.romanow.brs.database.DBStudent;
import me.romanow.brs.database.DBTutor;
import me.romanow.brs.database.DBUser;

public class TutorWindow extends javax.swing.JFrame {

    private AdminWindow parent=null;
    private TableComboBox permissionList=new TableComboBox();
    private TableComboBox ratingList=new TableComboBox();
   
    public TutorWindow(AdminWindow parent0) throws Throwable {
        initComponents();
        setTitle("Разрешения");
        this.parent = parent0;
        setBounds(250, 220, 350, 180);
        parent.studentItem=null;
        permissionList=new TableComboBox(PermissionList, new DBPermission(),new TableChoiceListener(){
        public void onSelect(DBItem item) {
            parent.permissionItem = (DBPermission)item;
            }
        });
        permissionList.setList(parent.conn.getList(DBPermission.class,parent.tutorItem));       
        ratingList=new TableComboBox(RatingList, new DBRating(),new TableChoiceListener(){
        public void onSelect(DBItem item) {
            parent.ratingItem = (DBRating)item;
            ratingList.copyPosition(parent.ratingList);
            }
        });
        ratingList.setList(parent.conn.getList(DBRating.class));    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button2 = new javax.swing.JButton();
        button5 = new javax.swing.JButton();
        RatingList = new javax.swing.JComboBox();
        PermissionList = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        button2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        button2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable-mdpi/add.png"))); // NOI18N
        button2.setBorder(null);
        button2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button2MouseClicked(evt);
            }
        });
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        getContentPane().add(button2);
        button2.setBounds(260, 70, 30, 30);

        button5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        button5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable-mdpi/remove.png"))); // NOI18N
        button5.setBorder(null);
        button5.setName(""); // NOI18N
        button5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button5MouseClicked(evt);
            }
        });
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });
        getContentPane().add(button5);
        button5.setBounds(260, 30, 30, 30);

        RatingList.setEditable(true);
        RatingList.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(RatingList);
        RatingList.setBounds(20, 80, 220, 21);

        PermissionList.setEditable(true);
        PermissionList.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(PermissionList);
        PermissionList.setBounds(20, 30, 220, 21);

        jLabel1.setText("Рейтинги");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 60, 70, 14);

        jLabel2.setText("Разрешения");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 10, 70, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button2MouseClicked
        if (evt.getButton()==3){
            parent.onErrorMessage("Добавить разрешение");
        }
    }//GEN-LAST:event_button2MouseClicked

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        if (parent.ratingItem==null){
            parent.onErrorMessage("Не выбран рейтинг");
            return;
            }
        parent.addPermission();
        try {
            permissionList.setList(parent.conn.getList(DBPermission.class,parent.tutorItem));       
            permissionList.set0();
            } catch(Throwable ee){ parent.fatal(ee); }
        //dispose();
    }//GEN-LAST:event_button2ActionPerformed

    private void button5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button5MouseClicked
        if (evt.getButton()==3){
            parent.onErrorMessage("Удалить разрешение");
        }
    }//GEN-LAST:event_button5MouseClicked

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        if (parent.permissionItem==null){
            parent.onErrorMessage("Не выбрано разрешение");
            return;
            }
        parent.removePermission();
        try {
            permissionList.setList(parent.conn.getList(DBPermission.class,parent.tutorItem));       
            permissionList.set0();
            } catch(Throwable ee){ parent.fatal(ee); }
        //dispose();
    }//GEN-LAST:event_button5ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox PermissionList;
    private javax.swing.JComboBox RatingList;
    private javax.swing.JButton button2;
    private javax.swing.JButton button5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
